config/routes.rb
Blog::Application.routes.draw do
  match '/posts*id' => 'posts#show', as: :post, format: false
  resources :posts, :only => :index

  match '/rss.xml'        => 'posts#index',  as: :rss, format: 'xml'
  match '/robots.txt'     => 'home#robots',  as: :robots

  if Rails.env.test?
    # raises an error for testing 500's
    match '/error' => 'posts#error', as: :error
  end

  # Catch all renders 404 because rescue_from doesn't work
  match '*id' => 'home#not_found', format: false

  root to: 'home#index'
end

app/models/post.rb
require 'date'
require 'pathname_extensions'

# A blog post is a directory with an index.text document found within `root_path`.
class Post
  class Error < StandardError
    attr_reader :post
    def initialize(post, message)
      @post = post
      super("#{post.permalink}: #{message}")
    end
  end

  class << self
    # @!attribute [rw] root_path
    #   Pathname to directory to store and retrieve posts.
    #   Default `Rails.root`.
    #   @return [Pathname]
    attr_writer :root_path
    def root_path
      @root_path ||= Rails.root + 'posts'
      @root_path ||= Pathname.new(@root_path.expand_path)
    end

    def last_modified
      root_path.atime
    end

    # @param [Integer] count number of recent posts to return
    # @return [Array] count most recent posts
    def recent(count = 6)
      all.slice(0, count)
    end

    # @return [Array] posts found under `root_path`
    def all
      root_path.search('index.text').sort {|a,b| b <=> a}.map do |path|
        new(path.dirname)
      end
    end
  end

  include Comparable

  # @!attribute [r] permalink
  # @return [String] relative canonical url
  attr_reader :permalink

  # @param [String] uri file path or uri path. e.g.
  #   /YYYY/MM/DD/dasherized-title
  #   /home/jch/articles/2011/11/14/articles_path/index.html
  def initialize(uri)
    @permalink = normalized_permalink(uri)
    @renderer  = Redcarpet::Markdown.new(Redcarpet::Render::XHTML, {
      no_intra_emphasis: true,
      fenced_code_blocks: true
    })
  end

  # Raw file contents of an index file
  #
  # @param [Pathname] dir directory to look for file
  # @return [String] index file contents. nil if not found
  def raw
    return nil unless directory
    @raw ||= directory.children.detect {|path|
      path.basename.to_s =~ /index.text/i
    }.read
  rescue Errno::ENOENT => e
    nil
  end

  # Normalizes directory names in `root_path` to find
  # a matching directory for the given permalink
  #
  # @return [Pathname] directory that holds permalink, nil if not found
  def directory
    # concatenate relative path to root_path
    dir, base  = (self.class.root_path + permalink.gsub(/^\//, '')).split
    normalized = base.to_s.upcase

    match = nil
    dir.find do |path|
      if path.basename.to_s.dasherize.upcase == normalized
        match = path
        Find.prune  # stop find
      end
    end
    @directory ||= match
  rescue Errno::ENOENT => e
    nil
  end

  # @return [Boolean] whether post directory exists with content
  def exists?
    !raw.nil?
  end

  # @return [String] title of post, first h1 line
  def title
    raw.split("\n").detect {|line|
      line =~ /\s/
    }.strip.gsub(/^#\s*/, '').gsub(/\s*#/, '')
  rescue => e
    raise Error.new(self, e.message)
  end

  # @return [String] publish date based on permalink
  def date
    Date.strptime permalink.match(%r{^/\d{4}/\d{2}/\d{2}})[0], '/%Y/%m/%d'
  end

  # @return [Datetime] last modified date
  def updated_at
    directory.mtime
  end

  # @return [String] html excerpt of the post
  def description
    @parsed_html ||= Nokogiri::HTML(html)
    @parsed_html.css('body').children.slice(1..-1).map(&:to_s).map(&:strip).join('')
  end

  # @return [String] html of entire post
  def html
    @html ||= @renderer.render(raw)
  end

  # Compares posts by permalink
  def <=>(post)
    permalink <=> post.permalink
  end

  protected

  # Normalize a directory path to a permalink string
  #
  # @param [Pathname, String] path
  # @return [String] permalink
  def normalized_permalink(path)
    path.to_s.
      gsub(self.class.root_path.to_s, '').   # relative path
      gsub(/[_,!@#\$^*?]/, '-').  # dasherize
      gsub(/index\.html$/, '').   # remove trailing index.html
      gsub(/\/$/, '').            # remove trailing /
      downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  if Rails.env.production?
    rescue_from Exception do |e|
      Rails.logger.error(e)
      (e.backtrace || []).each do |line|
        Rails.logger.error(line)
      end
      notify_airbrake(e)
      render template: 'home/error', status: 500
    end
  end

  # @return [String] base url of request
  def base_url
    URI.parse(request.url).tap {|u| u.path = ''}.to_s
  end

  # @return [String] full url of request
  def full_url
    base_url + request.path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # Homepage
  def index
    @posts = Post.recent(6)
    fresh_when last_modified: Post.last_modified, public: true
  end

  # 404 Not found page
  def not_found
    response.status = 404
  end

  def robots
    robots = <<-ROBOTS
Sitemap: #{URI.join(base_url, 'sitemap_index.xml.gz')}
ROBOTS
    render text: robots, content_type: 'text/plain'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # Archive page
  #
  # @return [Hash] posts keyed by month and year. e.g. 'June 2012'
  def index
    @title = "Archived Posts"
    # TODO: the ordering of the hash is implicit here
    @posts = Post.all.inject({}) do |memo, post|
      key = post.date.strftime('%B %Y')
      memo[key] ||= []
      memo[key] << post
      memo
    end
  end

  # Find a Post by permalink, render as html
  #
  # @param [String] :id canonical post permalink
  def show
    @post = Post.new(params[:id])

    if @post.exists?
      @title = @post.title
      fresh_when last_modified: @post.updated_at, public: true
    else
      render nothing: true, status: 404
    end
  end

  # Raises an exception for testing 500's in test environment
  def error
    raise "something went wrong"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/error.html.haml
%h1 Oops, something went wrong

%p
  If you think this page used to exist, but isn't working,
  please #{link_to "let me know", 'mailto:jch@whatcodecraves.com'} - Jerry

%p
  = link_to 'Home', root_path

app/views/home/index.html.haml
%h2 Writing

%ul.posts
  - @posts.each do |post|
    %li
      = link_to post.title, post_path(post.permalink)

  %li
    = link_to "Archived Posts", posts_path

%h2 Projects

%p Here's a sampling of projects I've started or worked on.

%ul.posts
  %li
    = link_to 'grape', 'https://github.com/intridea/grape'
    \- An opinionated micro-framework for creating REST-like APIs in Ruby
  %li
    = link_to 'rack-stream', 'https://github.com/intridea/rack-stream'
    \- Rack middleware for building multi-protocol streaming endpoints
  %li
    = link_to 'em-irc', 'https://github.com/jch/em-irc'
    \- Ruby EventMachine IRC client
  %li
    = link_to 'faraday', 'https://github.com/technoweenie/faraday'
    \- multi-adapter Ruby HTTP client with middleware support

app/views/home/not_found.html.haml
%h1 Oops, this link doesn't exist

%p
  If you think this page used to exist, but isn't working,
  please #{link_to "let me know", 'mailto:jch@whatcodecraves.com'} - Jerry

%p
  = link_to 'Home', root_path

app/views/layouts/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
  var disqus_shortname  = 'whatcodecraves';
  var disqus_title      = '<%=j disqus.title %>';
  var disqus_identifier = '<%=j post_path(disqus.permalink) %>';
  <% if Rails.env.development? %>
  var disqus_developer  = 1;
  <% end %>


  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/layouts/_header.html.haml
#header
  = link_to 'whatcodecraves.com', root_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta(content="width=device-width, initial-scale=1.0" name="viewport")
    %title
      = @title || "Jerry Cheung's Tech Portfolio"

    = stylesheet_link_tag "application", :media => "all"
    = render partial: 'layouts/analytics', formats: [:js]
    = yield(:head) if content_for?(:head)

  %body.container-fluid
    #wcc.full-width
      = content_for?(:header) ? yield(:header) : render('layouts/header')

      #main
        = render partial: 'layouts/carbon_ad'
        = yield

      #footer
        %p
          Copyright Jerry Cheung 2007 - #{Time.now.year} &nbsp;&nbsp;
          = link_to 'Source for this blog', 'https://github.com/jch/whatcoderaves.com'

app/views/layouts/home.html.haml
- content_for :header do
  #intro
    .content
      %p
        I'm Jerry. I love making stuff for the web and
        <a href='https://github.com/jch'>sharing it</a>.
      %p
        Offline, I'll never refuse a cold beer, delicious food, or
        laid-back company. I also have an unhealthy
        <a href='http://rockyroadblog.com'/>obsession with cars</a>.

      .social
        %a.email(href='mailto:jollyjerry@gmail.com')
        %a.github(href='https://github.com/jch')
        %a.twitter(href='http://twitter.com/whatcodecraves')
        %a.rss(href='http://feeds.feedburner.com/whatcodecraves')

= render template: 'layouts/application'

app/views/posts/index.html.haml
- @posts.each do |year, list|
  %h2= year
  %ul.posts
    - list.each do |post|
      %li= link_to post.title, post_path(post.permalink)

app/views/posts/show.html.haml
.post
  %h1= @post.title
  = link_to 'Vote on HN', "http://news.ycombinator.com/submit", class: 'hn-share-button'
  = link_to 'Tweet', "https://twitter.com/share", class: 'twitter-share-button', 'data_via' => 'whatcodecraves'
  .g-plus(data-action="share" data-annontation="bubble")
  = raw @post.description

= javascript_include_tag 'post'

:javascript
  hljs.initHighlightingOnLoad();

= render partial: 'layouts/sharing', formats: [:js]
= render partial: 'layouts/disqus', object: @post